name: Publish Release

on:
  push:
    tags:
      - "*"

env:
  PROJECT_NAME: better-fletching-table

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        run: |
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Archive Binaries
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: ${{ env.PROJECT_NAME }}-dpv${{ steps.get_tag.outputs.tag_name }}.zip
          exclusions: "**.git* /scripts/* **.jpeg notes.md"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PROJECT_NAME }}-dpv${{ steps.get_tag.outputs.tag_name }}.zip
            README.md
            LICENSE
